"""Prompts used by the guard and the benchmark. The benchmark caches Haiku outputs keyed
on the exact prompt text, so changing a string here invalidates those caches."""

QUESTION_INSTRUCTIONS = 'A cache stored the answer to cached_question. Would that exact same answer be a correct and complete answer to new_question? Answer yes only if one answer fits both questions. Answer no if the questions differ in anything that changes the answer, such as a negation or opposite, a different person, place, product or thing, a different number, time or date, or who or what the question applies to.'

CONV_INSTRUCTIONS = "A cache stored the assistant's reply to the final user message of the cached conversation. Would that exact same reply be a correct and complete reply to the final user message of the new conversation, given what was said earlier in each? Answer yes only if one reply fits both. Answer no if the earlier context makes the final messages refer to different things, such as a different product, account, order, number, date, place or person, or a different action being agreed to."

FACTS_PROMPT_V2 = 'You keep a compact running record of a customer-service conversation. It is used later to decide whether a cached reply can be reused for another conversation, so two records about the same situation must look the same, and two different situations must look different.\n\nGiven the current record (JSON) and the latest exchange, return the updated record as one JSON object and nothing else: no preamble, no code fence.\n\nUse exactly these keys:\n- "goal": the user\'s main request in this conversation (e.g. "book Tuesday 6:30pm spin class with Jo at IronWorks Bristol"). Keep it, with all its details, until it is completed or the user changes it. Side questions do not replace the goal.\n- "details": an object of the facts the goal depends on (company, branch, product, plan, item, reference numbers, dates, times, amounts, people, quantities). Copy every name, number, amount, date and time exactly as written in the conversation. Never paraphrase, round or recalculate them.\n- "current_question": what the user is asking about right now, if it differs from the goal, else "".\n- "pending": exactly what the assistant last offered, proposed or asked, including any options it listed (e.g. "offered 6:30pm or 8:15pm"), else "".\n\nUse short lower-case values. Ignore pleasantries and small talk.'

REWRITE_PROMPT = "Rewrite the user's final message as a standalone question or request that makes complete sense without the conversation. Keep names, IDs, numbers, dates, places, products and plans exactly as written. Return only the rewritten message."

REWRITE_LITE_PROMPT = "You get a summary of the earlier part of a customer-service conversation and its most recent messages. Rewrite the user's final message as a standalone question or request that makes complete sense on its own. Keep names, IDs, numbers, dates, places, products and plans exactly as written. Return only the rewritten message."

FACTS_BATCH_PROMPT = FACTS_PROMPT_V2.replace("the latest exchange", "the latest few exchanges")
