"""Generate js/src/shared.ts from the Python package, so the TypeScript port uses the
same prompts, thresholds and cost tables. The Python package is the source of truth.

  python scripts/gen_js_shared.py           # write js/src/shared.ts
  python scripts/gen_js_shared.py --check   # exit 1 if it's out of date (CI)
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from fow_cache import costs, guard, prompts  # noqa: E402

OUT = ROOT / "js" / "src" / "shared.ts"


def render():
    values = {
        "QUESTION_INSTRUCTIONS": prompts.QUESTION_INSTRUCTIONS,
        "CONV_INSTRUCTIONS": prompts.CONV_INSTRUCTIONS,
        "FACTS_BATCH_PROMPT": prompts.FACTS_BATCH_PROMPT,
        "REWRITE_LITE_PROMPT": prompts.REWRITE_LITE_PROMPT,
        "BATCH": guard.BATCH,
        "RECENT": guard.RECENT,
        "WHOLE_THRESHOLD": guard.WHOLE_THRESHOLD,
        "REWRITE_THRESHOLD": guard.REWRITE_THRESHOLD,
        "TIMEOUT_MS": int(guard.TIMEOUT * 1000),
        "PRICES": {k: list(v) for k, v in costs.PRICES.items()},
        "GUARD_MODEL": costs.GUARD_MODEL,
        "JEV_INPUT": costs.JEV_INPUT,
        "TOKENS": {size: {k: list(v) for k, v in t.items()} for size, t in costs.TOKENS.items()},
        "GUARDS": {k: list(v) for k, v in costs.GUARDS.items()},
    }
    lines = ["// Generated by scripts/gen_js_shared.py from the Python package. Do not edit.", ""]
    for name, value in values.items():
        lines.append(f"export const {name} = {json.dumps(value, ensure_ascii=False)} as const;")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit("js/src/shared.ts is out of date: run python scripts/gen_js_shared.py")
        print("js/src/shared.ts is up to date")
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(ROOT)}")
